### ISSUE TITLE
State.java:27: design State interface

### ISSUE THREAD

**Issue by 0pdd** [eo-cqrs/cmig#37]
The puzzle `32-b32bc0c2` from #32 has to be resolved: 

https://github.com/eo-cqrs/cmig/blob/8d1946dee42e847762438f4f56608f81f3ab8d2e/src/main/java/io/github/eocqrs/cmig/State.java#L27-L27

The puzzle was created by @rultor on 11-Aug-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment]
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-08-21T10:29:21.394172``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@l3r8yJ Don't forget to close this ticket before the deadline (2023-08-21T10:29:21). You are past the first half of the allowed period.

**Comment by 0pdd** [comment]
The puzzle `32-b32bc0c2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#49](https://github.com/eo-cqrs/cmig/issues/49), [#50](https://github.com/eo-cqrs/cmig/issues/50) are still not solved.

**Comment by zoeself** [comment]
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#49](https://github.com/eo-cqrs/cmig/issues/49) is still not solved; solved: [#50](https://github.com/eo-cqrs/cmig/issues/50).
